name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.7-dind
        options: >-
          --dns 8.8.8.8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8 black isort mypy
          flake8 app/
          black --check app/
          isort --check app/
          mypy app/

      - name: Test
        run: |
          pip install pytest pytest-cov
          pytest --cov=app

      - name: Build Docker image
        run: |
          docker build -t openaimedvision:ci .

      - name: Docker Compose up (smoke test)
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 10
          curl --fail http://localhost:8000/health
          docker compose down

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .coverage* 